version: '3.8'

services:
  twitch-miner:
    build: .
    container_name: twitch-miner
    environment:
      - TWITCH_USERNAME=${TWITCH_USERNAME:-}
      - STREAMER_FILE=${STREAMER_FILE:-ruststreamers.txt}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-}
      - MAKE_PREDICTIONS=${MAKE_PREDICTIONS:-false}
      - BET_PERCENTAGE=${BET_PERCENTAGE:-5}
      - BET_MAX_POINTS=${BET_MAX_POINTS:-50000}
      - BET_MINIMUM_POINTS=${BET_MINIMUM_POINTS:-20000}
    volumes:
      # Mount credential files (create these on host)
      - ./pass.txt:/usr/src/app/pass.txt:ro
      - ./ruststreamers.txt:/usr/src/app/ruststreamers.txt:ro
      - ./bo6streamers.txt:/usr/src/app/bo6streamers.txt:ro
      - ./xdefstreamers.txt:/usr/src/app/xdefstreamers.txt:ro
      # Mount cookies directory for persistence
      - ./cookies:/usr/src/app/cookies
      # Mount logs directory for persistence
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    # Add security options for Chrome
    security_opt:
      - seccomp:unconfined
    # Disable sandboxing for Chrome in container
    cap_add:
      - SYS_ADMIN